function Jacobian_P = Jacobian_PNumeric(L_b,L_e,L_u,P_x,P_y,P_z,thetaA1,thetaA2,thetaA3)
%JACOBIAN_PNUMERIC
%    JACOBIAN_P = JACOBIAN_PNUMERIC(L_B,L_E,L_U,P_X,P_Y,P_Z,THETAA1,THETAA2,THETAA3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Feb-2019 11:19:39

t2 = L_b./2.0;
t3 = sin(thetaA1);
t4 = L_e./2.0;
t5 = P_x.*2.0;
t6 = P_y.*2.0;
t7 = sqrt(3.0);
t8 = sin(thetaA2);
t9 = P_z.*2.0;
Jacobian_P = reshape([L_e.*(-1.0./2.0)+t2+t5-L_u.*t3,t2-t4+t5-L_u.*t8,-L_b+L_e+t5+L_u.*sin(thetaA3).*2.0,t6-t7.*(-t2+t4+L_u.*t3),t6+t7.*(-t2+t4+L_u.*t8),t6,t9+L_u.*cos(thetaA1).*2.0,t9+L_u.*cos(thetaA2).*2.0,t9+L_u.*cos(thetaA3).*2.0],[3,3]);
